project:
  type: website
  output-dir: docs
  render:
  - index.qmd
  - reading_list.qmd
  - lab_1.qmd
  - tutorial_sheet_1.qmd
  - tutorial_sheet_1_solutions.qmd
  - notes/notes_1.qmd
  - notes/notes_2.qmd
  - notes/notes_3.qmd
  - notes/supl_1.qmd
  - notes/Bayesian_computing.qmd
  - slides/Intro_EnvEco.qmd
  - slides/Understanding_Data.qmd
  - slides/Sampling.qmd
website:
  title: "Module 1"
  page-footer:
    center: '<a href="https://envstats-stats4009-stats503.github.io/Course_Notes/2025_26/Module_1/docs/" style="color:#ccc;">Home</a>'
  navbar:
    logo: UofG.png
    right:
      - text: "Home"
        href: index.qmd
    left:
      - text: "Notes"
        menu:
          - text: "Week 1 - Introduction"
            href:  notes/notes_1.qmd
          - text: "Week 2 - Understanding our Data"
            href:  notes/notes_2.qmd
          - text: "Week 3 - Sampling & Monitoring"
            href:  notes/notes_3.qmd
      - text: "Slides"
        menu:
          - text: "Week 1 - Introduction"
            href: slides/Intro_EnvEco.qmd
          - text: "Week 2 - Understanding our Data"
            href: slides/Understanding_Data.qmd
          - text: "Week 3 - Sampling & Monitoring"
            href: slides/Sampling.qmd
      - text: "Supplementary Notes"
        menu:
          - text: "Properties of estimators"
            href:  notes/supl_1.qmd
          - text: "Bayesian computational methods"
            href:  notes/Bayesian_computing.qmd"
      - text: "Tutorials"
        menu:
          - text: "Tutorial sheet 1"
            href: tutorial_sheet_1.qmd
      - text: "Labs"
        menu:
          - text: "Lab 1"
            href: lab_1.qmd
      - text: "Reading List"
        href: reading_list.qmd
format:
  html:
    mainfont: serif
    theme:
      light: flatly
      dark: darkly
    css:
      - styles.css
      - include/webex.css
    toc: true
    include-after-body: include/webex.js
editor: visual
