{
  "hash": "de658c32a568b62c9fe86a3af7c9dcf3",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Modelling Environmental Extremes\"\nembed-resources: false\nformat:\n  revealjs:\n    footer: '<a href=\"https://envstats-stats4009-stats503.github.io/Course_Notes/2025_26/Module_2/docs/\" style=\"color:#ccc; padding:20px 30px; display:inline-block; margin:-20px -30px;\">Home</a>'\n    margin: 0\n    logo:  UofG.png\n    theme: uofg_theme.scss\n    chalkboard: true\n    header-includes: |\n      <script src=\"custom.js\" type=\"application/javascript\"></script>\ntitle-slide-attributes: \n  data-background-image: uog_cloistures2.jpg\n  data-background-color: \"#FFFFFF\"\nslide-number: true\ninclude-in-header: \n  text: |\n    <style>\n      .custom-small table {\n        font-size: .8em\n      }\n      .custom-tiny table {\n        font-size: .6em\n      }\n    </style>\nauthor:\n  - name: Jafet Belmont \n    email: jafet.BelmontOsuna@glasgow.ac.uk \n    affiliations: School of Mathematics and Statistics\neditor_options: \n  chunk_output_type: console\nexecute: \n  freeze: auto\n  echo: true\nfilters:\n  - shinylive\n---\n\n\n\n\n##  {background-image=\"river.png\"}\n\n::: {.blockquote style=\"color: #FFFFFF; background-color:rgb(38, 38, 38,0.8); font-size: 1.25em; padding: 20px; border-radius: 5px;\"}\n> \"*On the subject of climate change, the data clearly show that Earth is warming up, and that humans are contributing to the warming. That’s the fairest assessment of the evidence.*\"\n>\n> Neil deGrasse Tyson\n:::\n\n## Recap\n\n-   For the last two weeks, we have looked at time series, and how appropriate models can be fitted that deal with the temporal structures in the data.\n-   In some cases, we want to specifically look at the maxima or minima of a particular environmental system.\n-   This week, we will look at methods for modelling these statistical **extremes**.\n\n## Extremes\n\n::: incremental\n-   We are trying to model rare events - by their very definition we won't have a lot of data on these.\n-   The bulk of the data in any statistical distribution will be in the centre.\n-   Standard density estimation techniques (e.g., the normal distribution) work well where the data have the greatest density, but that's not what we need here.\n-   We need to use a statistical model which is good at estimating the **tails** of our distribution.\n:::\n\n## Motivation\n\nStatistical modelling of extreme environmental phenomena has a very practical motivation: reliability - anything we build needs to have a good chance of surviving the weather/environment for the whole of its working life.\n\nThis has obvious implications for civil engineers and planners. They need to know:\n\n-   how strong to make buildings;\n-   how high to build sea walls;\n-   how tall to build reservoir dams;\n-   how much fuel to stockpile.\n\n## Motivation (continued)\n\nThis motivates the need to estimate what the:\n\n-   strongest wind;\n-   highest tide;\n-   heaviest rainfall;\n-   most severe cold-spell;\n\netc. will be over some fixed period of future time.\n\nThe only sensible way to do this is to use data on the variable of interest (wind, rain etc.) and fit an appropriate statistical model.\n\nThe models themselves are motivated by asymptotic theory, and this is our starting point.\n\n## What are your thoughts?\n\n[![Join mentimeter](images/clipboard-2550031199.png){fig-align=\"center\" width=\"507\"}](https://www.mentimeter.com/app/presentation/ala1dxpjj9pohdx9wer2rzuz2pnyh1zq/edit?question=zxmy3dkor82k){target=\"_blank\"}\n\n## Environmental extremes in our life\n\nEnvironmental extreme events are closer than you think...\n\n![](figures/eowyn_example.png){fig-align=\"center\" width=\"100%\"}\n\n## Environmental extremes in our life\n\n![](figures/extreme_examples.png){fig-align=\"center\" width=\"100%\"}\n\n## Defining an extreme {.smaller auto-animate=\"true\" background-color=\"#FFFFFF\"}\n\n-   The first thing we have to consider is what actually represents an *extreme* observation.\n-   This will vary depending on the context of the dataset.\n\n::::: columns\n::: {.column width=\"50%\"}\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](slides_6_files/figure-revealjs/unnamed-chunk-1-1.png){fig-align='center' width=384}\n:::\n:::\n\n\n\n:::\n\n::: {.column width=\"50%\"}\n-   We could just look at the biggest (or smallest) values.\n-   If so, over what time period?\n:::\n:::::\n\n## Defining an extreme {.smaller auto-animate=\"true\" background-color=\"#FFFFFF\"}\n\n-   The first thing we have to consider is what actually represents an *extreme* observation.\n-   This will vary depending on the context of the dataset.\n\n::::: columns\n::: {.column width=\"50%\"}\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](slides_6_files/figure-revealjs/unnamed-chunk-2-1.png){fig-align='center' width=384}\n:::\n:::\n\n\n\n:::\n\n::: {.column width=\"50%\"}\n-   We could just look at the biggest (or smallest) values.\n-   If so, over what time period? Annual maximum? Over the whole dataset? Both?\n:::\n:::::\n\n## Defining an extreme {.smaller auto-animate=\"true\" background-color=\"#FFFFFF\"}\n\n-   The first thing we have to consider is what actually represents an *extreme* observation.\n-   This will vary depending on the context of the dataset.\n\n::::: columns\n::: {.column width=\"50%\"}\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](slides_6_files/figure-revealjs/unnamed-chunk-3-1.png){fig-align='center' width=384}\n:::\n:::\n\n\n\n:::\n\n::: {.column width=\"50%\"}\n-   We could just look at the biggest (or smallest) values.\n-   If so, over what time period? Annual maximum? Over the whole dataset? Both?\n:::\n:::::\n\n## Defining an extreme {.smaller auto-animate=\"true\" background-color=\"#FFFFFF\"}\n\n-   The first thing we have to consider is what actually represents an *extreme* observation.\n-   This will vary depending on the context of the dataset.\n\n::::: columns\n::: {.column width=\"50%\"}\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](slides_6_files/figure-revealjs/unnamed-chunk-4-1.png){fig-align='center' width=384}\n:::\n:::\n\n\n\n:::\n\n::: {.column width=\"50%\"}\n-   We could just look at the biggest (or smallest) values.\n-   If so, over what time period? Annual maximum? Over the whole dataset? Both?\n-   Other times, it may be all observations above a certain threshold.\n:::\n:::::\n\n## Defining an extreme {.smaller auto-animate=\"true\" background-color=\"#FFFFFF\"}\n\n-   The first thing we have to consider is what actually represents an *extreme* observation.\n-   This will vary depending on the context of the dataset.\n\n::::: columns\n::: {.column width=\"50%\"}\n![](figures/sea_level_thresholds.gif){fig-align=\"center\"}\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n:::\n\n::: {.column width=\"50%\"}\n-   We could just look at the biggest (or smallest) values.\n-   If so, over what time period? Annual maximum? Over the whole dataset? Both?\n-   Other times, it may be all observations above a certain threshold.\n-   But then how to select the threshold?\n:::\n:::::\n\n## Extreme Value theory {.smaller}\n\n::: {style=\"height: 50px;\"}\n:::\n\nExtreme value modelling has a central theoretical result, analogous to the Central Limit Theorem...\n\n-   Suppose we have a series of random variables $X_1, \\ldots, X_n$, each with cumulative distribution function $F$, where $F(x) = \\text{P}(X \\leq x).$\n-   We can define the maximum of this set of random variables as $M_n = \\max{\\{ X_1, \\ldots, X_n\\}}$.\n-   Then we can show that $\\text{P}(M_n \\leq x) = P(X_1 \\leq x, \\ldots X_n \\leq x) = \\{F(x)\\}^n = F^n(x)$\n-   The block maxima approach focuses on understanding and estimating this function $F(x)$\n\n## Extreme Value Theory {.smaller}\n\n::: incremental\n-   The true cumulative distribution function, $F(x)$, is unknown.\n\n-   We could replace it with an estimate, but:\n\n    -   Any small differences between the estimate and the truth for $F(x)$ could lead to large differences in $F^n(x)$.\n    -   As $n \\to \\infty$ then the value of $F^n(x)$ will be 0 or 1 depending on whether $F(x) <1$ or $F(x)=1$. This means that the limit distribution of the maxima is a degenerate distribution.\n\n-   Instead, we tend to focus on the limiting distribution of $F^n(x)$ as $n \\to \\infty$, .i.e., the *limiting distribution of the normalized maximum* by introducing some constants to stabilize the maximum as $n$ grows.\n\n-   This is a distribution $G(x)$ such that, for constants $a_n > 0$ and $b_n$,\n\n    $$\\text{P}\\left(\\frac{M_n - b_n}{a_n} \\leq x\\right) = F^n(a_n x + b_n) \\to G(x) \\text{ as } n \\to \\infty$$\n\n    $G$ belongs to the type of one of three distribution functions.\n:::\n\n## Extreme Value Distributions\n\nThere are three main families of extreme value distribution which have our desired properties as limiting distributions of $F^n(x)$.\n\n**Gumbel**: $G(x) = \\exp \\left( -\\exp [\\frac{-(x-a_n)}{b_n} ]\\right)$\n\n**Fréchet**: $G(x) = \\exp \\left( -[\\frac{(x-a_n)}{b_n} ]^{-\\xi}\\right)$ for $z>b_n$, 0 otherwise.\n\n**Weibull**: $G(x) = \\exp \\left( -[\\frac{-(x-a_n)}{b_n} ]^{\\xi}\\right)$ for $z>b_n$, 1 otherwise.\n\nHere, $a_n$ is a location parameter, $b_n$ is a scale parameter and $\\xi$ is a shape parameter.\n\n# Block Maxima\n\n## Block Maxima\n\n-   A lot of investigation of environmental extremes will focus on time series data.\n-   Within time series data, we typically have natural groupings or blocks of observations (days, months, years etc).\n-   Therefore a common approach for modelling extremes focuses on the idea of **block maxima** - identifying the maximum (or minimum) value in each block.\n-   For example, if we have daily temperature data measured over 100 years, we could look at the highest temperature in each year.\n\n## Block Maxima Approach\n\n::: incremental\n-   Break up our sequence $X_1,X_2,\\ldots$ into blocks of size $n$ (with $n$ reasonably large), and extract only the maximum observation from each block.\n-   Now we fit $G(x)$ to the sequence of extracted maxima $M_{(1)},M_{(2)},\\ldots , M_{(N)}$ and use this as the basis for statistical inference.\n-   For example, consider the annual maxima of daily rainfall. Here our blocks have $n=365$ observations, which is reasonably large, so we fit our model to $N$ annual maxima (where $N$ is the number of years).\n-   This rough and ready approach has shown itself to be surprisingly robust.\n:::\n\n## The GEV Distribution\n\n-   More generally, we can model the maxima using the Generalised Extreme Value (GEV) distribution: $$G(x) = \\exp \\left( - \\left[ 1 + \\frac{\\xi (x - \\mu)}{\\sigma} \\right]^{-\\frac{1}{\\xi}} \\right)$$\n-   Here, $\\mu$ is the location parameter, $\\sigma$ is the scale parameter and $\\xi$ is the shape parameter.\n-   The Gumbel, Fréchet and Weibull distributions are all special cases depending on the value of $\\xi$.\n\n## The GEV Distribution {background-color=\"#FFFFFF\"}\n\n::::: columns\n::: {.column width=\"50%\"}\n$$G(x) = \\exp \\left( - \\left[ 1 + \\frac{\\xi (x - \\mu)}{\\sigma} \\right]^{-\\frac{1}{\\xi}} \\right)$$\n\n-   If $\\xi < 0$ then we have the Weibull distribution.\n-   If $\\xi > 0$ then we have the Fréchet distribution.\n-   As $\\xi \\to 0$ then we have the Gumbel distribution.\n:::\n\n::: {.column width=\"50%\"}\n![](figures/GEV.png){width=\"100%\" fig-align=\"center\"}\n:::\n:::::\n\n## Example\n\nIn this course we will focus on the statistical inference of real data for which the underlying distribution $F(\\cdot)$ is unknown.\n\nThus, the following example just illustrates how the choice of normalizing constants lead to a limit distribution within the GEV family.\n\n::: {.callout-note icon=\"false\"}\n## Example\n\nLet $X_1,\\ldots,X_n \\overset{iid}{\\sim} F$, where $F$ is Uniform(0,1). If we set the normalizing constants as:\n\n$$\na_n = \\frac{1}{n} ~~~~~b_n=1,\n$$\n\nthe limiting distribution of the maxima $M_n$ as $n\\to \\infty$ is a GEV with $\\mu= -1$ ,$\\sigma = 1$ and $\\xi = -1$\n:::\n\n## Example: Solution {.smaller}\n\nRecall that if $X_1,X_2,\\ldots$ are a sequence of independent uniform U(0, 1) then, $F(x) = x ~(\\text{for } 0 \\leq x \\leq 1)$\n\n$$\n\\begin{aligned}\n\\mathbb{Pr}\\left(\\dfrac{M_n -b_n}{a_n}\\leq x \\right) & = \\mathbb{Pr}(M_n \\leq b_n +a_n x)\\\\\n&= F\\left(b_n +a_n x\\right)^n\\\\\n& \\class{fragment}{= F\\left(1 + \\frac{1}{n}x\\right)^n}\\\\\n& \\class{fragment}{= \\left(1 + \\frac{1}{n}x\\right)^n ~~~\\text{for } 0 \\leq 1 + x/n   \\leq 1}\\\\\n\\end{aligned}\n$$\n\n## Example: Solution {.smaller}\n\nRecall that if $X_1,X_2,\\ldots$ are a sequence of independent uniform U(0, 1) then, $F(x) = x ~(\\text{for } 0 \\leq x \\leq 1)$\n\n$$\n\\begin{aligned}\n\\mathbb{Pr}\\left(\\dfrac{M_n -b_n}{a_n}\\leq x \\right) & = \\mathbb{Pr}(M_n \\leq b_n +a_n x)\\\\\n&= F\\left(b_n +a_n x\\right)^n\\\\\n&= F\\left(1 + \\frac{1}{n}x\\right)^n\\\\\n&= \\left(1 + \\frac{1}{n}x\\right)^n ~~~\\text{for } 0 \\leq 1 + x/n   \\leq 1\\\\\n& \\class{fragment}{ \\rightarrow \\exp x~ \\text{as }  n \\to \\infty}\n\\end{aligned}\n$$\n\n::: fragment\nUsing the fact that\n\n$$\n\\lim_{n \\to \\infty}\\left( 1 + \\frac{1}{n} x\\right)^n  = \\exp{x}\n$$\n:::\n\n## Example: Solution {.smaller}\n\nRecall that if $X_1,X_2,\\ldots$ are a sequence of independent uniform U(0, 1) then, $F(x) = x ~(\\text{for } 0 \\leq x \\leq 1)$\n\n$$\n\\begin{aligned}\n\\mathbb{Pr}\\left(\\dfrac{M_n -b_n}{a_n}\\leq x \\right) & = \\mathbb{Pr}(M_n \\leq b_n +a_n x)\\\\\n&= F\\left(b_n +a_n x\\right)^n\\\\\n&= F\\left(1 + \\frac{1}{n}x\\right)^n\\\\\n&= \\left(1 + \\frac{1}{n}x\\right)^n ~~~\\text{for } 0 \\leq 1 + x/n   \\leq 1\\\\\n&  \\rightarrow \\exp x~ \\text{as }  n \\to \\infty\n\\end{aligned}\n$$\n\n::: fragment\nLet $G(x) = \\exp \\left\\{- (1 + \\xi \\frac{x -\\mu}{\\sigma})^{-1/xi}\\right\\}$, setting $\\mu= -1$ ,$\\sigma = 1$ and $\\xi = -1$ leads to:\n:::\n\n::: fragment\n$$\nG(x) =  \\exp \\left\\{- (1 -x + 1 )\\right\\} = \\exp x\n$$\n:::\n\n## Generating samples from Block Maxima in R {background-color=\"#FFFFFF\"}\n\n::: {style=\"font-size: 80%;\"}\n\n\n\n::: {.cell layout-align=\"center\" output-location='column'}\n\n```{.r .cell-code}\ngenerate.max <- function(N = 50,n=5,\n                         rdist,param=c(0,1),\n                         a=1,b=0,seed=pi){\n  set.seed(seed)\n  Mn <- c()\n  for(i in 1:N){\n    sample <- rdist(n,param[1],param[2])\n    Mn[i]<- (max(sample)-b)/a\n  }\n  hist(Mn,breaks = \"FD\",\n       col=\"lightblue\",proba=T,\n       main=\"Histogram of maximums\",xlab='')\n}\n\ngenerate.max(N=50000,n=5,rdist=runif,\n             param=c(0,1),a=1/5,b=1)\ncurve(ExtremalDep::dGEV(x,-1,1,-1),type=\"l\",\n      n=500,add=T,lwd=3,lty=1,col=2)\n```\n\n::: {.cell-output-display}\n![](slides_6_files/figure-revealjs/unnamed-chunk-6-1.png){fig-align='center' width=384}\n:::\n:::\n\n\n\n:::\n\n## Generating samples from Block Maxima in R\n\n::: {style=\"height: 50px;\"}\n:::\n\n::::: {style=\"font-size: 80%;\"}\n::: {.callout-note icon=\"false\"}\nFor $X_1,\\ldots,X_n \\overset{iid}{\\sim} F$, where $F$ is Uniform(0,1), if we normalise the maximum using $b_n=1$ and $a_n=1/n$, we know that the asymptotic distribution of $\\dfrac{M_n -b_n}{a_n}$ is a GEV($\\mu$=−1,$\\sigma$=1,$\\xi$=−1).\n:::\n\n::: {.callout-note icon=\"false\"}\nLikewise, if $X_1, X_2 , \\ldots$ is a sequence of independent standard exponential $Exp(1)$ variables, using $b_n=1$ and $a_n=\\log n$ the asymptotic distribution of the normalised maxima is a GEV($\\mu=0,\\sigma=1,\\xi=0$) i.e., a Gumbell distribution.\n:::\n\n-   Let’s see what this looks like, for a few different values of n\n:::::\n\n## Generating samples from Block Maxima in R {background-color=\"#FFFFFF\"}\n\n```{shinylive-r}\n#| standalone: true\n#| viewerHeight: 500\n\nlibrary(shiny)\n\n# Function to generate block maxima\ngenerate_max <- function(N, n, rdist, param, a, b, seed=pi){\n  set.seed(seed)\n  Mn <- numeric(N)\n  for(i in 1:N){\n    sample <- rdist(n, param[1], param[2])\n    Mn[i] <- (max(sample) - b) / a\n  }\n  return(Mn)\n}\n\n# UI\niu <- fluidPage(\n  titlePanel(\"Block Maxima Simulation\"),\n  sidebarLayout(\n    sidebarPanel(\n      selectInput(\"dist\", \"Choose Distribution:\", choices = c(\"Uniform(0,1)\" = \"uniform\", \"Exponential(1)\" = \"exponential\")),\n      sliderInput(\"n\", \"Observations per Block (n):\", min = 5, max = 100, value = 5, step = 5),\n      sliderInput(\"N\", \"Number of Blocks (N):\", min = 10000, max = 50000, value = 50000, step = 10000)\n    ),\n    mainPanel(\n      plotOutput(\"histogram\")\n    )\n  )\n)\n\n# Server\nserver <- function(input, output) {\n  output$histogram <- renderPlot({\n    if (input$dist == \"uniform\") {\n      a <- 1 / input$n\n      b <- 1\n      Mn <- generate_max(input$N, input$n, runif, c(0,1), a, b)\n      true_gev <- function(x) evd::dgev(x, loc = -1, scale = 1, shape = -1)\n    } else {\n      a <- 1\n      b <- log(input$n)\n      Mn <- generate_max(input$N, input$n, rgamma, c(1,1), a, b)\n      true_gev <- function(x) evd::dgev(x, loc = 0, scale = 1, shape = 0)\n    }\n    \n    hist(Mn, breaks = \"FD\", col = \"lightblue\", prob = TRUE, main = \"Histogram of Block Maxima\", xlab = \"Maxima\")\n    curve(true_gev, col = \"red\", lwd = 2, add = TRUE)\n  })\n}\n\n# Run App\nshinyApp(ui = iu, server = server)\n\n```\n\n## Maxima and Minima {.smaller background-color=\"#FFFFFF\"}\n\n-   Communication of extremes typically focuses on maxima (or minima).\n-   Environmental or climate events are often described as the \"worst/highest/lowest in X years\".\n\n::::: columns\n::: {.column width=\"50%\"}\n![](figures/EuropeDrought.png){width=\"100%\"}\n:::\n\n::: {.column width=\"50%\"}\n![](figures/BangladeshFloods.png){width=\"100%\"}\n:::\n:::::\n\n## Return Levels\n\n::: incremental\n-   In statistics, this idea of the \"highest in X years\" can be related to the idea of a **return level** and **return period**.\n-   The return level $z_p$ is the value we would expect to be exceeded once every $p$ years, where $\\frac{1}{p}$ is the return period.\n-   The return level can also be thought of as the value which has probability $\\frac{1}{p}$ of being exceeded in a given year.\n-   Now consider the statement: *\"The temperature in Glasgow will reach 20 degrees once every 50 years\"*.\n-   Here, we have return period $\\frac{1}{50}=0.02$ and return level $z_p=20$.\n:::\n\n## Return Levels and the GEV\n\n-   The return level $z_p$ is the $(1-\\frac{1}{p})$ quantile of the GEV distribution, since we have a probability $\\frac{1}{p}$ of the maximum exceeding that value, i.e., $P(M_n > z_p) = \\frac{1}{p}$.\n-   Recall that the GEV takes the form $$\n    \\begin{aligned}\n    G(z_p) &= \\begin{cases} \n      \\exp \\left( - \\left[ 1 + \\frac{\\xi (z_p - \\mu)}{\\sigma} \\right]^{-\\frac{1}{\\xi}} \\right) &, \\xi \\neq 0 \\\\\n      \\exp\\left(-\\exp\\left(-\\frac{z_p-\\mu}{\\sigma}\\right)\\right) &, \\xi = 0 \n    \\end{cases}\\\\\n    G(z_p) &= P(M_n \\leq z_p) = 1 - P(M_n > z_p)\n    \\end{aligned}\n    $$\n-   Therefore the return level can be obtained by inverting this distribution to obtain $$\n    z_p = \\begin{cases}\n      \\mu - \\frac{\\sigma}{\\xi}\\left[ 1 - \\{ -\\log(1-\\frac{1}{p}) \\}^\\xi \\right] & \\xi \\neq 0\\\\\n      \\mu - \\sigma \\log\\{ -\\log(1-\\frac{1}{p})\\} & \\xi = 0\n    \\end{cases}\n    $$\n\n## Example - Venice Sea Levels {background-color=\"#FFFFFF\"}\n\n::::: columns\n::: {.column width=\"45%\"}\n-   Sea levels in Venice are rising.\n-   The city floods on a regular basis.\n-   What sea level can we expect in the next 5, 10, 100 years?\n:::\n\n::: {.column width=\"55%\"}\n![](figures/GuardianVenice.png){width=\"100%\"}\n:::\n:::::\n\n## Example - Venice Sea Levels {background-color=\"#FFFFFF\"}\n\n-   We have daily sea level measurements from 1931-1981.\n-   The plot below shows the 10 highest sea level measurements from each year.\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](slides_6_files/figure-revealjs/unnamed-chunk-7-1.png){fig-align='center' width=384}\n:::\n:::\n\n\n\n\n## Example - Venice Sea Levels {background-color=\"#FFFFFF\"}\n\n-   We can apply a block maxima approach, treating each year as a block.\n-   This requires us to identify and model the yearly maximum.\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](slides_6_files/figure-revealjs/unnamed-chunk-8-1.png){fig-align='center' width=384}\n:::\n:::\n\n\n\n\n## Fitting the GEV in R {background-color=\"#FFFFFF\"}\n\n-   We use the `extRemes` package to fit a GEV distribution in R\n-   The `fevd()` simply takes a data vector of the annual maxima and provides parameter estimates using maximum likelihood estimation.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(extRemes)\nMn <- apply(venice[,-1],1,function(x)max(x,na.rm = T))\nfit_gev <- fevd(Mn,method=\"MLE\")\nfit_gev$results$par\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    location        scale        shape \n111.09726863  17.17910050  -0.07678211 \n```\n\n\n:::\n:::\n\n\n\n\n-   From the output we can see that $\\mu = 111.1$, $\\sigma = 17.2$ and $\\xi = -0.077$.\n\n## Return Level Plot {.smaller background-color=\"#FFFFFF\"}\n\n-   We can assess the suitability of the GEV distribution using a return level plot.\n-   This involves commuting the return level at various return periods, and comparing it to the theoretical result under the GEV.\n\n:::::: columns\n:::: {.column width=\"45%\"}\n::: incremental\n-   The observed points lie along the theoretical line.\n-   Our proposed GEV distribution is appropriate.\n-   The Venice maxima follow a Gumbel distribution.\n:::\n::::\n\n::: {.column width=\"55%\"}\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot(fit_gev, type = \"rl\")\n```\n\n::: {.cell-output-display}\n![](slides_6_files/figure-revealjs/unnamed-chunk-10-1.png){fig-align='center' width=432}\n:::\n:::\n\n\n\n:::\n::::::\n\n## Extending Block Maxima - $k$-largest {background-color=\"#FFFFFF\"}\n\n-   Looking at just the maxima means we throw away a lot of data, making it harder to accurately estimate parameters.\n-   We could instead follow an approach which models the $k$ largest values within a block.\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](slides_6_files/figure-revealjs/unnamed-chunk-11-1.png){fig-align='center' width=576}\n:::\n:::\n\n\n\n\n## Choice of Block Size\n\n::: incremental\n-   We have to make difficult subjective choices when fitting a block maxima model.\n-   What do we choose as our block? Week? Month? Year? Decade?\n-   Bigger blocks means we have fewer data points, but smaller blocks mean our 'extremes' might not be extreme at all, violating the assumptions of the GEV distribution.\n-   If we use a $k$-largest approach, we have a similar decision on what value of $k$ to choose.\n:::\n\n# Peak Over Threshold\n\n## Drawbacks of Block Maxima\n\n-   Block maxima methods work well in many situations, and take advantage of natural blocks in the data.\n-   However, it does not work well if there is a lot of variability between blocks.\n-   In that scenario, some blocks may have many more large counts than others, and much of the data will be discarded.\n-   We can overcome this by using a threshold approach, which models all observations which exceed some pre-specified value.\n\n## Peak Over Threshold\n\n-   This approach is known as **peak over threshold (POT)** modelling.\n-   Again, we assume we have data represented by a time series, and some threshold $u$.\n-   We need a statistical model for the values which are above $u$, known as **exceedances**.\n-   Sometimes we may also wish to model the *number* of exceedances.\n\n## Peak Over Threshold {background-color=\"#FFFFFF\"}\n\n-   Again, let $X_1, \\ldots, X_n$ be a sequence of independent random variables with a common distribution function $F$.\n-   We can consider our extreme values in terms of their **threshold excess** (how much they exceed the threshold by).\n-   For an extreme value $X > u$, its threshold excess is given as $y = X - u$.\n\n![](figures/POT.png){width=\"100%\"}\n\n## Peak Over Threshold\n\nThe probability of threshold excess of size $y$ is given by\n\n$$\n\\begin{aligned}\nP(X > u+y~|~X > u) &= \\frac{P(X>u+y)}{P(X>u)} \\quad\\text{where } y > 0\\\\\n &=  \\frac{1 - F(u + y)}{1 - F(u)}\n\\end{aligned}\n$$\n\n![](figures/POT2.png){width=\"50%\" fig-align=\"center\"}\n\n## Generalised Pareto\n\n-   The function $F$ is still unknown, but the distribution of all threshold excesses can be approximated by a **Generalised Pareto distribution (GPD)**.\n-   The cdf of the Generalised Pareto distribution is given by $$\n    P(X \\leq y~|~X>u) = G(y) = \n    \\begin{cases}\n    1 - \\left( 1 + \\frac{\\xi (y-u)}{\\sigma} \\right)^{-\\frac{1}{\\xi}} & \\xi \\neq 0\\\\\n    1 - \\exp \\left( - \\frac{y-u}{\\sigma} \\right) & \\xi = 0\n    \\end{cases}\n    $$\n-   Again, $u$ is the location parameter, $\\sigma$ is the scale parameter and $\\xi$ is the shape parameter.\n\n## Return Levels for POT Models\n\n-   We can define a return level for POT models in a roughly similar way to block maxima models.\n-   The $m$-observation return level, $x_m$ is defined as the level expected to be exceeded once every $m$ observations, with $$\n    x_m = \n    \\begin{cases}\n    u + \\frac{\\sigma}{\\xi} \\left[ \\left(m P(X>u)\\right)^\\xi - 1 \\right] & \\xi \\neq 0\\\\\n    u + \\sigma \\log\\left(m P(X>u)\\right) & \\xi = 0\n    \\end{cases}\n    $$\n-   For any given observation, the probability of exceeding $x_m$ is simply $\\frac{1}{m}$.\n\n## Derivation of the return level when $\\xi=0$ {.smaller}\n\n:::::: columns\n::: {.column width=\"40%\"}\nRecall that\n\n1.  the probability of exceeding $x_m$ is given by\n\n$$\n\\begin{aligned}\n\\mathbb{Pr}(x > x_m) &= \\mathbb{Pr}(x > x_m|x > u)\\mathbb{Pr}(x>u) \\\\\n&= 1/m\n\\end{aligned}\n$$\n\n2.  the GEV with $\\xi = 0$ is\n\n$$\\underbrace{G(x_m)}_{\\mathbb{Pr}(x\\leq x_m | x >u)} = 1- \\underbrace{\\exp \\left(-\\dfrac{x_m -u}{\\sigma}\\right)}_{\\mathbb{Pr}(x>x_m|x>u)}$$\n:::\n\n:::: {.column width=\"60%\"}\n::: {style=\"height: 50px;\"}\n:::\n\n$$\n\\begin{aligned}\n\\mathbb{Pr}(x > x_m) &= \\mathbb{Pr}(x > x_m|x > u)\\mathbb{Pr}(x>u)\\\\\n& \\class{fragment}{ = \\exp \\left(-\\dfrac{x_m -u}{\\sigma}\\right) \\mathbb{Pr}(x>u) = \\frac{1}{m}}\\\\\n& \\class{fragment}{ \\Rightarrow ~ \\exp \\left(-\\dfrac{x_m -u}{\\sigma}\\right) = \\dfrac{1}{m\\mathbb{Pr}(x>u)}}\\\\\n& \\class{fragment}{-\\dfrac{x_m -u}{\\sigma}= \\log (1) -\\log (m\\mathbb{Pr}(x>u))} \\\\\n  &~~~~~~~~~~~~~~~~~~~\\class{fragment}{\\vdots} \\\\\n &~~~~~~~~~~~~ \\class{fragment}{x_m =  u + \\sigma \\log (m\\mathbb{Pr}(x>u))}\n\\end{aligned}\n$$\n::::\n::::::\n\n## Choosing a Threshold {background-color=\"#FFFFFF\"}\n\n-   We need a threshold low enough that we have sufficient data, but high enough that values above it are genuinely extreme.\n\n![](figures/Thresholds.png){width=\"65%\" fig-align=\"center\"}\n\n## Choosing a Threshold\n\n::: incremental\n-   Occasionally there is a natural choice of threshold (e.g., a legal limit for a pollutant), but generally we need to choose it.\n-   One approach is to use a **mean residual life plot**, which plots the sample mean excess (mean of $x>u$) at a variety of thresholds $u$.\n-   If the GPD is appropriate, the mean excess should be linearly related to the threshold.\n-   Therefore, we can identify a suitable threshold as one which lies within an area of linearity on this plot.\n:::\n\n## Example - Fort Collins, Colorado {background-color=\"#FFFFFF\"}\n\n-   We have daily precipitation data from 1900-1999, obtained from a rain gauge in Fort Collins, Colorado, taken from Katz et al, 2002.\n\n![](figures/FortCollinsData.png){fig-align=\"center\"}\n\n## Example - Fort Collins, Colorado {background-color=\"#FFFFFF\"}\n\nWe compare three different choices of threshold below ($u = 0.5, 1.0, 1.5$) to show the importance of getting the choice right.\n\n::::: columns\n::: {.column width=\"70%\"}\n![](figures/FortCollinsThresholds.png){width=\"100%\" fig-aligna=\"center\"}\n:::\n\n::: {.column width=\"30%\"}\n| $u$ | $\\% > u$ | $n > u$ |\n|-----|----------|---------|\n| 0.5 | 2.08     | 759     |\n| 1.0 | 0.58     | 213     |\n| 1.5 | 0.25     | 91      |\n:::\n:::::\n\n## Mean Residual Life Plot {background-color=\"#FFFFFF\"}\n\n-   We can fit a mean residual life plot to identify a sensible choice of threshold.\n-   It appears that a value of $u$ somewhere between 1.2 and 1.8 would be an appropriate choice here - this is where the plot appears to be linear.\n\n![](figures/MeanResidualPlot.png){width=\"100%\" fig-align=\"center\"}\n\n## Sensitivity Analysis {background-color=\"#FFFFFF\"}\n\n-   We can also carry out a sensitivity analysis to see the effect of choosing different threshold values on the estimated model parameters.\n-   The plot below shows the parameter estimates at different thresholds - they seem fairly robust.\n\n![](figures/Sensitivity.png){width=\"60%\" fig-align=\"center\"}\n\n## POT Models in R\n\n-   We can use the `extRemes` package to fit a Generalised Pareto distribution in R.\n-   The function `fevd` allows several extreme value distributions (including GEV and GPD) to be fitted, and can also provide return levels.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfitGP <- fevd(Fort, threshold=1.5, type=\"GP\",\n                    time.units=\"365/year\")\n\nreturn.level(fitGP, c(10,20,100), type=\"GP\")\n```\n:::\n\n\n\n\n```         \n[1] \"Return Levels for period units in years\"\n 10-year level  20-year level 100-year level\n      2.857184       3.340219       4.581339\n```\n\n## Correlation\n\n::: incremental\n-   Threshold exceedances are not always independent due to temporal correlation.\n\n-   If we have high temperatures today, it's likely we might also have high temperatures tomorrow.\n\n-   We have to account for this dependence within our model, for example by using the autoregressive approaches outlined in the time series section.\n\n-   Alternatively, we could use a 'declustering' approach which identifies these temporal clusters and simply uses the cluster maxima.\n:::\n\n## Summary\n\n::: incremental\n-   Estimating extremes is challenging and the results can be unreliable even with large datasets.\n\n-   We have identified two main approaches for dealing with these data - block maxima and point over threshold.\n\n-   The block maxima approach uses the Generalised Extreme Value (GEV) distribution to model the highest value(s) within a specific block of time.\n\n-   The point over threshold approach uses the Generalised Pareto distribution (GPD) to model all observations which exceed a certain value.\n:::\n",
    "supporting": [
      "slides_6_files\\figure-revealjs"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}