<!DOCTYPE html>
<html lang="en"><head>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<meta name="shinylive:serviceworker_dir" content="..">
<script src="../site_libs/quarto-contrib/shinylive-0.9.1/shinylive/load-shinylive-sw.js" type="module"></script>
<script src="../site_libs/quarto-contrib/shinylive-0.9.1/shinylive/run-python-blocks.js" type="module"></script>
<link href="../site_libs/quarto-contrib/shinylive-0.9.1/shinylive/shinylive.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/shinylive-quarto-css/shinylive-quarto.css" rel="stylesheet"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.6.42">

  <meta name="author" content="Jafet Belmont">
  <title>Module 2 – Modelling Environmental Extremes</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-fc987e72ae1d3a70a7ffe212e2cb94cf.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <style>
    .custom-small table {
      font-size: .8em
    }
    .custom-tiny table {
      font-size: .6em
    }
  </style>
  <script src="custom.js" type="application/javascript"></script>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" data-background-color="#FFFFFF" data-background-image="uog_cloistures2.jpg" class="quarto-title-block center">
  <h1 class="title">Modelling Environmental Extremes</h1>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Jafet Belmont 
</div>
<div class="quarto-title-author-email">
<a href="mailto:jafet.BelmontOsuna@glasgow.ac.uk">jafet.BelmontOsuna@glasgow.ac.uk</a>
</div>
        <p class="quarto-title-affiliation">
            School of Mathematics and Statistics
          </p>
    </div>
</div>

</section>
<section id="section" class="slide level2" data-background-image="river.png">
<h2></h2>
<div class="blockquote" style="color: #FFFFFF; background-color:rgb(38, 38, 38,0.8); font-size: 1.25em; padding: 20px; border-radius: 5px;">
<blockquote>
<p>“<em>On the subject of climate change, the data clearly show that Earth is warming up, and that humans are contributing to the warming. That’s the fairest assessment of the evidence.</em>”</p>
<p>Neil deGrasse Tyson</p>
</blockquote>
</div>
</section>
<section id="recap" class="slide level2">
<h2>Recap</h2>
<ul>
<li>For the last two weeks, we have looked at time series, and how appropriate models can be fitted that deal with the temporal structures in the data.</li>
<li>In some cases, we want to specifically look at the maxima or minima of a particular environmental system.</li>
<li>This week, we will look at methods for modelling these statistical <strong>extremes</strong>.</li>
</ul>
</section>
<section id="extremes" class="slide level2">
<h2>Extremes</h2>
<div>
<ul>
<li class="fragment">We are trying to model rare events - by their very definition we won’t have a lot of data on these.</li>
<li class="fragment">The bulk of the data in any statistical distribution will be in the centre.</li>
<li class="fragment">Standard density estimation techniques (e.g., the normal distribution) work well where the data have the greatest density, but that’s not what we need here.</li>
<li class="fragment">We need to use a statistical model which is good at estimating the <strong>tails</strong> of our distribution.</li>
</ul>
</div>
</section>
<section id="motivation" class="slide level2">
<h2>Motivation</h2>
<p>Statistical modelling of extreme environmental phenomena has a very practical motivation: reliability - anything we build needs to have a good chance of surviving the weather/environment for the whole of its working life.</p>
<p>This has obvious implications for civil engineers and planners. They need to know:</p>
<ul>
<li>how strong to make buildings;</li>
<li>how high to build sea walls;</li>
<li>how tall to build reservoir dams;</li>
<li>how much fuel to stockpile.</li>
</ul>
</section>
<section id="motivation-continued" class="slide level2">
<h2>Motivation (continued)</h2>
<p>This motivates the need to estimate what the:</p>
<ul>
<li>strongest wind;</li>
<li>highest tide;</li>
<li>heaviest rainfall;</li>
<li>most severe cold-spell;</li>
</ul>
<p>etc. will be over some fixed period of future time.</p>
<p>The only sensible way to do this is to use data on the variable of interest (wind, rain etc.) and fit an appropriate statistical model.</p>
<p>The models themselves are motivated by asymptotic theory, and this is our starting point.</p>
</section>
<section id="what-are-your-thoughts" class="slide level2">
<h2>What are your thoughts?</h2>
<div class="quarto-figure quarto-figure-center">
<figure>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><a href="https://www.mentimeter.com/app/presentation/ala1dxpjj9pohdx9wer2rzuz2pnyh1zq/edit?question=zxmy3dkor82k" target="_blank"><img data-src="images/clipboard-2550031199.png" class="quarto-figure quarto-figure-center" width="507" alt="Join mentimeter"></a></p>
</figure>
</div>
<figcaption>Join mentimeter</figcaption>
</figure>
</div>
</section>
<section id="environmental-extremes-in-our-life" class="slide level2">
<h2>Environmental extremes in our life</h2>
<p>Environmental extreme events are closer than you think…</p>

<img data-src="figures/eowyn_example.png" class="quarto-figure quarto-figure-center r-stretch" style="width:100.0%"></section>
<section id="environmental-extremes-in-our-life-1" class="slide level2">
<h2>Environmental extremes in our life</h2>

<img data-src="figures/extreme_examples.png" class="quarto-figure quarto-figure-center r-stretch" style="width:100.0%"></section>
<section id="defining-an-extreme" class="slide level2 smaller" data-auto-animate="true" data-background-color="#FFFFFF">
<h2 data-id="quarto-animate-title">Defining an extreme</h2>
<ul>
<li>The first thing we have to consider is what actually represents an <em>extreme</em> observation.</li>
<li>This will vary depending on the context of the dataset.</li>
</ul>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="slides_6_files/figure-revealjs/unnamed-chunk-1-1.png" class="quarto-figure quarto-figure-center" width="384"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<ul>
<li>We could just look at the biggest (or smallest) values.</li>
<li>If so, over what time period?</li>
</ul>
</div></div>
</section>
<section id="defining-an-extreme-1" class="slide level2 smaller" data-auto-animate="true" data-background-color="#FFFFFF">
<h2 data-id="quarto-animate-title">Defining an extreme</h2>
<ul>
<li>The first thing we have to consider is what actually represents an <em>extreme</em> observation.</li>
<li>This will vary depending on the context of the dataset.</li>
</ul>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="slides_6_files/figure-revealjs/unnamed-chunk-2-1.png" class="quarto-figure quarto-figure-center" width="384"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<ul>
<li>We could just look at the biggest (or smallest) values.</li>
<li>If so, over what time period? Annual maximum? Over the whole dataset? Both?</li>
</ul>
</div></div>
</section>
<section id="defining-an-extreme-2" class="slide level2 smaller" data-auto-animate="true" data-background-color="#FFFFFF">
<h2 data-id="quarto-animate-title">Defining an extreme</h2>
<ul>
<li>The first thing we have to consider is what actually represents an <em>extreme</em> observation.</li>
<li>This will vary depending on the context of the dataset.</li>
</ul>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="slides_6_files/figure-revealjs/unnamed-chunk-3-1.png" class="quarto-figure quarto-figure-center" width="384"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<ul>
<li>We could just look at the biggest (or smallest) values.</li>
<li>If so, over what time period? Annual maximum? Over the whole dataset? Both?</li>
</ul>
</div></div>
</section>
<section id="defining-an-extreme-3" class="slide level2 smaller" data-auto-animate="true" data-background-color="#FFFFFF">
<h2 data-id="quarto-animate-title">Defining an extreme</h2>
<ul>
<li>The first thing we have to consider is what actually represents an <em>extreme</em> observation.</li>
<li>This will vary depending on the context of the dataset.</li>
</ul>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="slides_6_files/figure-revealjs/unnamed-chunk-4-1.png" class="quarto-figure quarto-figure-center" width="384"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<ul>
<li>We could just look at the biggest (or smallest) values.</li>
<li>If so, over what time period? Annual maximum? Over the whole dataset? Both?</li>
<li>Other times, it may be all observations above a certain threshold.</li>
</ul>
</div></div>
</section>
<section id="defining-an-extreme-4" class="slide level2 smaller" data-auto-animate="true" data-background-color="#FFFFFF">
<h2 data-id="quarto-animate-title">Defining an extreme</h2>
<ul>
<li>The first thing we have to consider is what actually represents an <em>extreme</em> observation.</li>
<li>This will vary depending on the context of the dataset.</li>
</ul>
<div class="columns">
<div class="column" style="width:50%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figures/sea_level_thresholds.gif" class="quarto-figure quarto-figure-center"></p>
</figure>
</div>
</div><div class="column" style="width:50%;">
<ul>
<li>We could just look at the biggest (or smallest) values.</li>
<li>If so, over what time period? Annual maximum? Over the whole dataset? Both?</li>
<li>Other times, it may be all observations above a certain threshold.</li>
<li>But then how to select the threshold?</li>
</ul>
</div></div>
</section>
<section id="extreme-value-theory" class="slide level2 smaller">
<h2>Extreme Value theory</h2>
<div style="height: 50px;">

</div>
<p>Extreme value modelling has a central theoretical result, analogous to the Central Limit Theorem…</p>
<ul>
<li>Suppose we have a series of random variables <span class="math inline">\(X_1, \ldots, X_n\)</span>, each with cumulative distribution function <span class="math inline">\(F\)</span>, where <span class="math inline">\(F(x) = \text{P}(X \leq x).\)</span></li>
<li>We can define the maximum of this set of random variables as <span class="math inline">\(M_n = \max{\{ X_1, \ldots, X_n\}}\)</span>.</li>
<li>Then we can show that <span class="math inline">\(\text{P}(M_n \leq x) = P(X_1 \leq x, \ldots X_n \leq x) = \{F(x)\}^n = F^n(x)\)</span></li>
<li>The block maxima approach focuses on understanding and estimating this function <span class="math inline">\(F(x)\)</span></li>
</ul>
</section>
<section id="extreme-value-theory-1" class="slide level2 smaller">
<h2>Extreme Value Theory</h2>
<div>
<ul>
<li class="fragment"><p>The true cumulative distribution function, <span class="math inline">\(F(x)\)</span>, is unknown.</p></li>
<li class="fragment"><p>We could replace it with an estimate, but:</p>
<ul>
<li class="fragment">Any small differences between the estimate and the truth for <span class="math inline">\(F(x)\)</span> could lead to large differences in <span class="math inline">\(F^n(x)\)</span>.</li>
<li class="fragment">As <span class="math inline">\(n \to \infty\)</span> then the value of <span class="math inline">\(F^n(x)\)</span> will be 0 or 1 depending on whether <span class="math inline">\(F(x) &lt;1\)</span> or <span class="math inline">\(F(x)=1\)</span>. This means that the limit distribution of the maxima is a degenerate distribution.</li>
</ul></li>
<li class="fragment"><p>Instead, we tend to focus on the limiting distribution of <span class="math inline">\(F^n(x)\)</span> as <span class="math inline">\(n \to \infty\)</span>, .i.e., the <em>limiting distribution of the normalized maximum</em> by introducing some constants to stabilize the maximum as <span class="math inline">\(n\)</span> grows.</p></li>
<li class="fragment"><p>This is a distribution <span class="math inline">\(G(x)\)</span> such that, for constants <span class="math inline">\(a_n &gt; 0\)</span> and <span class="math inline">\(b_n\)</span>,</p>
<p><span class="math display">\[\text{P}\left(\frac{M_n - b_n}{a_n} \leq x\right) = F^n(a_n x + b_n) \to G(x) \text{ as } n \to \infty\]</span></p>
<p><span class="math inline">\(G\)</span> belongs to the type of one of three distribution functions.</p></li>
</ul>
</div>
</section>
<section id="extreme-value-distributions" class="slide level2">
<h2>Extreme Value Distributions</h2>
<p>There are three main families of extreme value distribution which have our desired properties as limiting distributions of <span class="math inline">\(F^n(x)\)</span>.</p>
<p><strong>Gumbel</strong>: <span class="math inline">\(G(x) = \exp \left( -\exp [\frac{-(x-a_n)}{b_n} ]\right)\)</span></p>
<p><strong>Fréchet</strong>: <span class="math inline">\(G(x) = \exp \left( -[\frac{(x-a_n)}{b_n} ]^{-\xi}\right)\)</span> for <span class="math inline">\(z&gt;b_n\)</span>, 0 otherwise.</p>
<p><strong>Weibull</strong>: <span class="math inline">\(G(x) = \exp \left( -[\frac{-(x-a_n)}{b_n} ]^{\xi}\right)\)</span> for <span class="math inline">\(z&gt;b_n\)</span>, 1 otherwise.</p>
<p>Here, <span class="math inline">\(a_n\)</span> is a location parameter, <span class="math inline">\(b_n\)</span> is a scale parameter and <span class="math inline">\(\xi\)</span> is a shape parameter.</p>
</section>
<section>
<section id="block-maxima" class="title-slide slide level1 center">
<h1>Block Maxima</h1>

</section>
<section id="block-maxima-1" class="slide level2">
<h2>Block Maxima</h2>
<ul>
<li>A lot of investigation of environmental extremes will focus on time series data.</li>
<li>Within time series data, we typically have natural groupings or blocks of observations (days, months, years etc).</li>
<li>Therefore a common approach for modelling extremes focuses on the idea of <strong>block maxima</strong> - identifying the maximum (or minimum) value in each block.</li>
<li>For example, if we have daily temperature data measured over 100 years, we could look at the highest temperature in each year.</li>
</ul>
</section>
<section id="block-maxima-approach" class="slide level2">
<h2>Block Maxima Approach</h2>
<div>
<ul>
<li class="fragment">Break up our sequence <span class="math inline">\(X_1,X_2,\ldots\)</span> into blocks of size <span class="math inline">\(n\)</span> (with <span class="math inline">\(n\)</span> reasonably large), and extract only the maximum observation from each block.</li>
<li class="fragment">Now we fit <span class="math inline">\(G(x)\)</span> to the sequence of extracted maxima <span class="math inline">\(M_{(1)},M_{(2)},\ldots , M_{(N)}\)</span> and use this as the basis for statistical inference.</li>
<li class="fragment">For example, consider the annual maxima of daily rainfall. Here our blocks have <span class="math inline">\(n=365\)</span> observations, which is reasonably large, so we fit our model to <span class="math inline">\(N\)</span> annual maxima (where <span class="math inline">\(N\)</span> is the number of years).</li>
<li class="fragment">This rough and ready approach has shown itself to be surprisingly robust.</li>
</ul>
</div>
</section>
<section id="the-gev-distribution" class="slide level2">
<h2>The GEV Distribution</h2>
<ul>
<li>More generally, we can model the maxima using the Generalised Extreme Value (GEV) distribution: <span class="math display">\[G(x) = \exp \left( - \left[ 1 + \frac{\xi (x - \mu)}{\sigma} \right]^{-\frac{1}{\xi}} \right)\]</span></li>
<li>Here, <span class="math inline">\(\mu\)</span> is the location parameter, <span class="math inline">\(\sigma\)</span> is the scale parameter and <span class="math inline">\(\xi\)</span> is the shape parameter.</li>
<li>The Gumbel, Fréchet and Weibull distributions are all special cases depending on the value of <span class="math inline">\(\xi\)</span>.</li>
</ul>
</section>
<section id="the-gev-distribution-1" class="slide level2" data-background-color="#FFFFFF">
<h2>The GEV Distribution</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><span class="math display">\[G(x) = \exp \left( - \left[ 1 + \frac{\xi (x - \mu)}{\sigma} \right]^{-\frac{1}{\xi}} \right)\]</span></p>
<ul>
<li>If <span class="math inline">\(\xi &lt; 0\)</span> then we have the Weibull distribution.</li>
<li>If <span class="math inline">\(\xi &gt; 0\)</span> then we have the Fréchet distribution.</li>
<li>As <span class="math inline">\(\xi \to 0\)</span> then we have the Gumbel distribution.</li>
</ul>
</div><div class="column" style="width:50%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figures/GEV.png" class="quarto-figure quarto-figure-center" style="width:100.0%"></p>
</figure>
</div>
</div></div>
</section>
<section id="example" class="slide level2">
<h2>Example</h2>
<p>In this course we will focus on the statistical inference of real data for which the underlying distribution <span class="math inline">\(F(\cdot)\)</span> is unknown.</p>
<p>Thus, the following example just illustrates how the choice of normalizing constants lead to a limit distribution within the GEV family.</p>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Example</strong></p>
</div>
<div class="callout-content">
<p>Let <span class="math inline">\(X_1,\ldots,X_n \overset{iid}{\sim} F\)</span>, where <span class="math inline">\(F\)</span> is Uniform(0,1). If we set the normalizing constants as:</p>
<p><span class="math display">\[
a_n = \frac{1}{n} ~~~~~b_n=1,
\]</span></p>
<p>the limiting distribution of the maxima <span class="math inline">\(M_n\)</span> as <span class="math inline">\(n\to \infty\)</span> is a GEV with <span class="math inline">\(\mu= -1\)</span> ,<span class="math inline">\(\sigma = 1\)</span> and <span class="math inline">\(\xi = -1\)</span></p>
</div>
</div>
</div>
</section>
<section id="example-solution" class="slide level2 smaller">
<h2>Example: Solution</h2>
<p>Recall that if <span class="math inline">\(X_1,X_2,\ldots\)</span> are a sequence of independent uniform U(0, 1) then, <span class="math inline">\(F(x) = x ~(\text{for } 0 \leq x \leq 1)\)</span></p>
<p><span class="math display">\[
\begin{aligned}
\mathbb{Pr}\left(\dfrac{M_n -b_n}{a_n}\leq x \right) &amp; = \mathbb{Pr}(M_n \leq b_n +a_n x)\\
&amp;= F\left(b_n +a_n x\right)^n\\
&amp; \class{fragment}{= F\left(1 + \frac{1}{n}x\right)^n}\\
&amp; \class{fragment}{= \left(1 + \frac{1}{n}x\right)^n ~~~\text{for } 0 \leq 1 + x/n   \leq 1}\\
\end{aligned}
\]</span></p>
</section>
<section id="example-solution-1" class="slide level2 smaller">
<h2>Example: Solution</h2>
<p>Recall that if <span class="math inline">\(X_1,X_2,\ldots\)</span> are a sequence of independent uniform U(0, 1) then, <span class="math inline">\(F(x) = x ~(\text{for } 0 \leq x \leq 1)\)</span></p>
<p><span class="math display">\[
\begin{aligned}
\mathbb{Pr}\left(\dfrac{M_n -b_n}{a_n}\leq x \right) &amp; = \mathbb{Pr}(M_n \leq b_n +a_n x)\\
&amp;= F\left(b_n +a_n x\right)^n\\
&amp;= F\left(1 + \frac{1}{n}x\right)^n\\
&amp;= \left(1 + \frac{1}{n}x\right)^n ~~~\text{for } 0 \leq 1 + x/n   \leq 1\\
&amp; \class{fragment}{ \rightarrow \exp x~ \text{as }  n \to \infty}
\end{aligned}
\]</span></p>
<div class="fragment">
<p>Using the fact that</p>
<p><span class="math display">\[
\lim_{n \to \infty}\left( 1 + \frac{1}{n} x\right)^n  = \exp{x}
\]</span></p>
</div>
</section>
<section id="example-solution-2" class="slide level2 smaller">
<h2>Example: Solution</h2>
<p>Recall that if <span class="math inline">\(X_1,X_2,\ldots\)</span> are a sequence of independent uniform U(0, 1) then, <span class="math inline">\(F(x) = x ~(\text{for } 0 \leq x \leq 1)\)</span></p>
<p><span class="math display">\[
\begin{aligned}
\mathbb{Pr}\left(\dfrac{M_n -b_n}{a_n}\leq x \right) &amp; = \mathbb{Pr}(M_n \leq b_n +a_n x)\\
&amp;= F\left(b_n +a_n x\right)^n\\
&amp;= F\left(1 + \frac{1}{n}x\right)^n\\
&amp;= \left(1 + \frac{1}{n}x\right)^n ~~~\text{for } 0 \leq 1 + x/n   \leq 1\\
&amp;  \rightarrow \exp x~ \text{as }  n \to \infty
\end{aligned}
\]</span></p>
<div class="fragment">
<p>Let <span class="math inline">\(G(x) = \exp \left\{- (1 + \xi \frac{x -\mu}{\sigma})^{-1/xi}\right\}\)</span>, setting <span class="math inline">\(\mu= -1\)</span> ,<span class="math inline">\(\sigma = 1\)</span> and <span class="math inline">\(\xi = -1\)</span> leads to:</p>
</div>
<div class="fragment">
<p><span class="math display">\[
G(x) =  \exp \left\{- (1 -x + 1 )\right\} = \exp x
\]</span></p>
</div>
</section>
<section id="generating-samples-from-block-maxima-in-r" class="slide level2" data-background-color="#FFFFFF">
<h2>Generating samples from Block Maxima in R</h2>
<div style="font-size: 80%;">
<div class="cell columns column-output-location" data-layout-align="center">
<div class="column">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a></a>generate.max <span class="ot">&lt;-</span> <span class="cf">function</span>(<span class="at">N =</span> <span class="dv">50</span>,<span class="at">n=</span><span class="dv">5</span>,</span>
<span id="cb1-2"><a></a>                         rdist,<span class="at">param=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>),</span>
<span id="cb1-3"><a></a>                         <span class="at">a=</span><span class="dv">1</span>,<span class="at">b=</span><span class="dv">0</span>,<span class="at">seed=</span>pi){</span>
<span id="cb1-4"><a></a>  <span class="fu">set.seed</span>(seed)</span>
<span id="cb1-5"><a></a>  Mn <span class="ot">&lt;-</span> <span class="fu">c</span>()</span>
<span id="cb1-6"><a></a>  <span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>N){</span>
<span id="cb1-7"><a></a>    sample <span class="ot">&lt;-</span> <span class="fu">rdist</span>(n,param[<span class="dv">1</span>],param[<span class="dv">2</span>])</span>
<span id="cb1-8"><a></a>    Mn[i]<span class="ot">&lt;-</span> (<span class="fu">max</span>(sample)<span class="sc">-</span>b)<span class="sc">/</span>a</span>
<span id="cb1-9"><a></a>  }</span>
<span id="cb1-10"><a></a>  <span class="fu">hist</span>(Mn,<span class="at">breaks =</span> <span class="st">"FD"</span>,</span>
<span id="cb1-11"><a></a>       <span class="at">col=</span><span class="st">"lightblue"</span>,<span class="at">proba=</span>T,</span>
<span id="cb1-12"><a></a>       <span class="at">main=</span><span class="st">"Histogram of maximums"</span>,<span class="at">xlab=</span><span class="st">''</span>)</span>
<span id="cb1-13"><a></a>}</span>
<span id="cb1-14"><a></a></span>
<span id="cb1-15"><a></a><span class="fu">generate.max</span>(<span class="at">N=</span><span class="dv">50000</span>,<span class="at">n=</span><span class="dv">5</span>,<span class="at">rdist=</span>runif,</span>
<span id="cb1-16"><a></a>             <span class="at">param=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>),<span class="at">a=</span><span class="dv">1</span><span class="sc">/</span><span class="dv">5</span>,<span class="at">b=</span><span class="dv">1</span>)</span>
<span id="cb1-17"><a></a><span class="fu">curve</span>(ExtremalDep<span class="sc">::</span><span class="fu">dGEV</span>(x,<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>,<span class="sc">-</span><span class="dv">1</span>),<span class="at">type=</span><span class="st">"l"</span>,</span>
<span id="cb1-18"><a></a>      <span class="at">n=</span><span class="dv">500</span>,<span class="at">add=</span>T,<span class="at">lwd=</span><span class="dv">3</span>,<span class="at">lty=</span><span class="dv">1</span>,<span class="at">col=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div><div class="column">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="slides_6_files/figure-revealjs/unnamed-chunk-6-1.png" class="quarto-figure quarto-figure-center" width="384"></p>
</figure>
</div>
</div>
</div></div>
</div>
</section>
<section id="generating-samples-from-block-maxima-in-r-1" class="slide level2">
<h2>Generating samples from Block Maxima in R</h2>
<div style="height: 50px;">

</div>
<div style="font-size: 80%;">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>For <span class="math inline">\(X_1,\ldots,X_n \overset{iid}{\sim} F\)</span>, where <span class="math inline">\(F\)</span> is Uniform(0,1), if we normalise the maximum using <span class="math inline">\(b_n=1\)</span> and <span class="math inline">\(a_n=1/n\)</span>, we know that the asymptotic distribution of <span class="math inline">\(\dfrac{M_n -b_n}{a_n}\)</span> is a GEV(<span class="math inline">\(\mu\)</span>=−1,<span class="math inline">\(\sigma\)</span>=1,<span class="math inline">\(\xi\)</span>=−1).</p>
</div>
</div>
</div>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Likewise, if <span class="math inline">\(X_1, X_2 , \ldots\)</span> is a sequence of independent standard exponential <span class="math inline">\(Exp(1)\)</span> variables, using <span class="math inline">\(b_n=1\)</span> and <span class="math inline">\(a_n=\log n\)</span> the asymptotic distribution of the normalised maxima is a GEV(<span class="math inline">\(\mu=0,\sigma=1,\xi=0\)</span>) i.e., a Gumbell distribution.</p>
</div>
</div>
</div>
<ul>
<li>Let’s see what this looks like, for a few different values of n</li>
</ul>
</div>
</section>
<section id="generating-samples-from-block-maxima-in-r-2" class="slide level2" data-background-color="#FFFFFF">
<h2>Generating samples from Block Maxima in R</h2>
<div class="sourceCode" id="cb2" data-engine="r"><pre class="sourceCode numberSource shinylive-r number-lines code-with-copy"><code class="sourceCode"><span id="cb2-1"><a></a>#| '!! shinylive warning !!': |</span>
<span id="cb2-2"><a></a>#|   shinylive does not work in self-contained HTML documents.</span>
<span id="cb2-3"><a></a>#|   Please set `embed-resources: false` in your metadata.</span>
<span id="cb2-4"><a></a>#| standalone: true</span>
<span id="cb2-5"><a></a>#| viewerHeight: 500</span>
<span id="cb2-6"><a></a></span>
<span id="cb2-7"><a></a>library(shiny)</span>
<span id="cb2-8"><a></a></span>
<span id="cb2-9"><a></a># Function to generate block maxima</span>
<span id="cb2-10"><a></a>generate_max &lt;- function(N, n, rdist, param, a, b, seed=pi){</span>
<span id="cb2-11"><a></a>  set.seed(seed)</span>
<span id="cb2-12"><a></a>  Mn &lt;- numeric(N)</span>
<span id="cb2-13"><a></a>  for(i in 1:N){</span>
<span id="cb2-14"><a></a>    sample &lt;- rdist(n, param[1], param[2])</span>
<span id="cb2-15"><a></a>    Mn[i] &lt;- (max(sample) - b) / a</span>
<span id="cb2-16"><a></a>  }</span>
<span id="cb2-17"><a></a>  return(Mn)</span>
<span id="cb2-18"><a></a>}</span>
<span id="cb2-19"><a></a></span>
<span id="cb2-20"><a></a># UI</span>
<span id="cb2-21"><a></a>iu &lt;- fluidPage(</span>
<span id="cb2-22"><a></a>  titlePanel("Block Maxima Simulation"),</span>
<span id="cb2-23"><a></a>  sidebarLayout(</span>
<span id="cb2-24"><a></a>    sidebarPanel(</span>
<span id="cb2-25"><a></a>      selectInput("dist", "Choose Distribution:", choices = c("Uniform(0,1)" = "uniform", "Exponential(1)" = "exponential")),</span>
<span id="cb2-26"><a></a>      sliderInput("n", "Observations per Block (n):", min = 5, max = 100, value = 5, step = 5),</span>
<span id="cb2-27"><a></a>      sliderInput("N", "Number of Blocks (N):", min = 10000, max = 50000, value = 50000, step = 10000)</span>
<span id="cb2-28"><a></a>    ),</span>
<span id="cb2-29"><a></a>    mainPanel(</span>
<span id="cb2-30"><a></a>      plotOutput("histogram")</span>
<span id="cb2-31"><a></a>    )</span>
<span id="cb2-32"><a></a>  )</span>
<span id="cb2-33"><a></a>)</span>
<span id="cb2-34"><a></a></span>
<span id="cb2-35"><a></a># Server</span>
<span id="cb2-36"><a></a>server &lt;- function(input, output) {</span>
<span id="cb2-37"><a></a>  output$histogram &lt;- renderPlot({</span>
<span id="cb2-38"><a></a>    if (input$dist == "uniform") {</span>
<span id="cb2-39"><a></a>      a &lt;- 1 / input$n</span>
<span id="cb2-40"><a></a>      b &lt;- 1</span>
<span id="cb2-41"><a></a>      Mn &lt;- generate_max(input$N, input$n, runif, c(0,1), a, b)</span>
<span id="cb2-42"><a></a>      true_gev &lt;- function(x) evd::dgev(x, loc = -1, scale = 1, shape = -1)</span>
<span id="cb2-43"><a></a>    } else {</span>
<span id="cb2-44"><a></a>      a &lt;- 1</span>
<span id="cb2-45"><a></a>      b &lt;- log(input$n)</span>
<span id="cb2-46"><a></a>      Mn &lt;- generate_max(input$N, input$n, rgamma, c(1,1), a, b)</span>
<span id="cb2-47"><a></a>      true_gev &lt;- function(x) evd::dgev(x, loc = 0, scale = 1, shape = 0)</span>
<span id="cb2-48"><a></a>    }</span>
<span id="cb2-49"><a></a>    </span>
<span id="cb2-50"><a></a>    hist(Mn, breaks = "FD", col = "lightblue", prob = TRUE, main = "Histogram of Block Maxima", xlab = "Maxima")</span>
<span id="cb2-51"><a></a>    curve(true_gev, col = "red", lwd = 2, add = TRUE)</span>
<span id="cb2-52"><a></a>  })</span>
<span id="cb2-53"><a></a>}</span>
<span id="cb2-54"><a></a></span>
<span id="cb2-55"><a></a># Run App</span>
<span id="cb2-56"><a></a>shinyApp(ui = iu, server = server)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="maxima-and-minima" class="slide level2 smaller" data-background-color="#FFFFFF">
<h2>Maxima and Minima</h2>
<ul>
<li>Communication of extremes typically focuses on maxima (or minima).</li>
<li>Environmental or climate events are often described as the “worst/highest/lowest in X years”.</li>
</ul>
<div class="columns">
<div class="column" style="width:50%;">
<p><img data-src="figures/EuropeDrought.png" style="width:100.0%"></p>
</div><div class="column" style="width:50%;">
<p><img data-src="figures/BangladeshFloods.png" style="width:100.0%"></p>
</div></div>
</section>
<section id="return-levels" class="slide level2">
<h2>Return Levels</h2>
<div>
<ul>
<li class="fragment">In statistics, this idea of the “highest in X years” can be related to the idea of a <strong>return level</strong> and <strong>return period</strong>.</li>
<li class="fragment">The return level <span class="math inline">\(z_p\)</span> is the value we would expect to be exceeded once every <span class="math inline">\(p\)</span> years, where <span class="math inline">\(\frac{1}{p}\)</span> is the return period.</li>
<li class="fragment">The return level can also be thought of as the value which has probability <span class="math inline">\(\frac{1}{p}\)</span> of being exceeded in a given year.</li>
<li class="fragment">Now consider the statement: <em>“The temperature in Glasgow will reach 20 degrees once every 50 years”</em>.</li>
<li class="fragment">Here, we have return period <span class="math inline">\(\frac{1}{50}=0.02\)</span> and return level <span class="math inline">\(z_p=20\)</span>.</li>
</ul>
</div>
</section>
<section id="return-levels-and-the-gev" class="slide level2" data-auto-animate="true">
<h2 data-id="quarto-animate-title">Return Levels and the GEV</h2>
<ul>
<li>The return level <span class="math inline">\(z_p\)</span> is the <span class="math inline">\((1-\frac{1}{p})\)</span> quantile of the GEV distribution, since we have a probability <span class="math inline">\(\frac{1}{p}\)</span> of the maximum exceeding that value, i.e., <span class="math inline">\(P(M_n &gt; z_p) = \frac{1}{p}\)</span>.</li>
<li>Recall that the GEV takes the form <span class="math display">\[
\begin{aligned}
G(z_p) &amp;= \begin{cases}
  \exp \left( - \left[ 1 + \frac{\xi (z_p - \mu)}{\sigma} \right]^{-\frac{1}{\xi}} \right) &amp;, \xi \neq 0 \\
  \exp\left(-\exp\left(-\frac{z_p-\mu}{\sigma}\right)\right) &amp;, \xi = 0
\end{cases}\\
G(z_p) &amp;= P(M_n \leq z_p) = 1 - P(M_n &gt; z_p)
\end{aligned}
\]</span></li>
</ul>
</section>
<section id="return-levels-and-the-gev-1" class="slide level2" data-auto-animate="true">
<h2 data-id="quarto-animate-title">Return Levels and the GEV</h2>
<ul>
<li><p>The return level <span class="math inline">\(z_p\)</span> is the <span class="math inline">\((1-\frac{1}{p})\)</span> quantile of the GEV distribution, since we have a probability <span class="math inline">\(\frac{1}{p}\)</span> of the maximum exceeding that value, i.e., <span class="math inline">\(P(M_n &gt; z_p) = \frac{1}{p}\)</span>.</p></li>
<li><p>Recall that the GEV takes the form <span class="math display">\[
\begin{aligned}
G(z_p) &amp;= P(M_n \leq z_p) = 1 - P(M_n &gt; z_p)
\end{aligned}
\]</span></p></li>
<li><p>Therefore the return level can be obtained by inverting this distribution to obtain <span class="math display">\[
z_p = \begin{cases}
  \mu - \frac{\sigma}{\xi}\left[ 1 - \{ -\log(1-\frac{1}{p}) \}^\xi \right] &amp; \xi \neq 0\\
  \mu - \sigma \log\{ -\log(1-\frac{1}{p})\} &amp; \xi = 0
\end{cases}
\]</span></p></li>
</ul>
</section>
<section id="example---venice-sea-levels" class="slide level2" data-background-color="#FFFFFF">
<h2>Example - Venice Sea Levels</h2>
<div class="columns">
<div class="column" style="width:45%;">
<ul>
<li>Sea levels in Venice are rising.</li>
<li>The city floods on a regular basis.</li>
<li>What sea level can we expect in the next 5, 10, 100 years?</li>
</ul>
</div><div class="column" style="width:55%;">
<p><img data-src="figures/GuardianVenice.png" style="width:100.0%"></p>
</div></div>
</section>
<section id="example---venice-sea-levels-1" class="slide level2" data-background-color="#FFFFFF">
<h2>Example - Venice Sea Levels</h2>
<ul>
<li>We have daily sea level measurements from 1931-1981.</li>
<li>The plot below shows the 10 highest sea level measurements from each year.</li>
</ul>

<img data-src="slides_6_files/figure-revealjs/unnamed-chunk-7-1.png" class="quarto-figure quarto-figure-center r-stretch" width="384"></section>
<section id="example---venice-sea-levels-2" class="slide level2" data-background-color="#FFFFFF">
<h2>Example - Venice Sea Levels</h2>
<ul>
<li>We can apply a block maxima approach, treating each year as a block.</li>
<li>This requires us to identify and model the yearly maximum.</li>
</ul>

<img data-src="slides_6_files/figure-revealjs/unnamed-chunk-8-1.png" class="quarto-figure quarto-figure-center r-stretch" width="384"></section>
<section id="fitting-the-gev-in-r" class="slide level2" data-background-color="#FFFFFF">
<h2>Fitting the GEV in R</h2>
<ul>
<li>We use the <code>extRemes</code> package to fit a GEV distribution in R</li>
<li>The <code>fevd()</code> simply takes a data vector of the annual maxima and provides parameter estimates using maximum likelihood estimation.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a></a><span class="fu">library</span>(extRemes)</span>
<span id="cb3-2"><a></a>Mn <span class="ot">&lt;-</span> <span class="fu">apply</span>(venice[,<span class="sc">-</span><span class="dv">1</span>],<span class="dv">1</span>,<span class="cf">function</span>(x)<span class="fu">max</span>(x,<span class="at">na.rm =</span> T))</span>
<span id="cb3-3"><a></a>fit_gev <span class="ot">&lt;-</span> <span class="fu">fevd</span>(Mn,<span class="at">method=</span><span class="st">"MLE"</span>)</span>
<span id="cb3-4"><a></a>fit_gev<span class="sc">$</span>results<span class="sc">$</span>par</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    location        scale        shape 
111.09726863  17.17910050  -0.07678211 </code></pre>
</div>
</div>
<ul>
<li>From the output we can see that <span class="math inline">\(\mu = 111.1\)</span>, <span class="math inline">\(\sigma = 17.2\)</span> and <span class="math inline">\(\xi = -0.077\)</span>.</li>
</ul>
</section>
<section id="return-level-plot" class="slide level2 smaller" data-background-color="#FFFFFF">
<h2>Return Level Plot</h2>
<ul>
<li>We can assess the suitability of the GEV distribution using a return level plot.</li>
<li>This involves commuting the return level at various return periods, and comparing it to the theoretical result under the GEV.</li>
</ul>
<div class="columns">
<div class="column" style="width:45%;">
<div>
<ul>
<li class="fragment">The observed points lie along the theoretical line.</li>
<li class="fragment">Our proposed GEV distribution is appropriate.</li>
<li class="fragment">The Venice maxima follow a Gumbel distribution.</li>
</ul>
</div>
</div><div class="column" style="width:55%;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a></a><span class="fu">plot</span>(fit_gev, <span class="at">type =</span> <span class="st">"rl"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="slides_6_files/figure-revealjs/unnamed-chunk-10-1.png" class="quarto-figure quarto-figure-center" width="432"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="extending-block-maxima---k-largest" class="slide level2" data-background-color="#FFFFFF">
<h2>Extending Block Maxima - <span class="math inline">\(k\)</span>-largest</h2>
<ul>
<li>Looking at just the maxima means we throw away a lot of data, making it harder to accurately estimate parameters.</li>
<li>We could instead follow an approach which models the <span class="math inline">\(k\)</span> largest values within a block.</li>
</ul>

<img data-src="slides_6_files/figure-revealjs/unnamed-chunk-11-1.png" class="quarto-figure quarto-figure-center r-stretch" width="576"></section>
<section id="choice-of-block-size" class="slide level2">
<h2>Choice of Block Size</h2>
<div>
<ul>
<li class="fragment">We have to make difficult subjective choices when fitting a block maxima model.</li>
<li class="fragment">What do we choose as our block? Week? Month? Year? Decade?</li>
<li class="fragment">Bigger blocks means we have fewer data points, but smaller blocks mean our ‘extremes’ might not be extreme at all, violating the assumptions of the GEV distribution.</li>
<li class="fragment">If we use a <span class="math inline">\(k\)</span>-largest approach, we have a similar decision on what value of <span class="math inline">\(k\)</span> to choose.</li>
</ul>
</div>
</section></section>
<section>
<section id="peak-over-threshold" class="title-slide slide level1 center">
<h1>Peak Over Threshold</h1>

</section>
<section id="drawbacks-of-block-maxima" class="slide level2">
<h2>Drawbacks of Block Maxima</h2>
<ul>
<li>Block maxima methods work well in many situations, and take advantage of natural blocks in the data.</li>
<li>However, it does not work well if there is a lot of variability between blocks.</li>
<li>In that scenario, some blocks may have many more large counts than others, and much of the data will be discarded.</li>
<li>We can overcome this by using a threshold approach, which models all observations which exceed some pre-specified value.</li>
</ul>
</section>
<section id="peak-over-threshold-1" class="slide level2">
<h2>Peak Over Threshold</h2>
<ul>
<li>This approach is known as <strong>peak over threshold (POT)</strong> modelling.</li>
<li>Again, we assume we have data represented by a time series, and some threshold <span class="math inline">\(u\)</span>.</li>
<li>We need a statistical model for the values which are above <span class="math inline">\(u\)</span>, known as <strong>exceedances</strong>.</li>
<li>Sometimes we may also wish to model the <em>number</em> of exceedances.</li>
</ul>
</section>
<section id="peak-over-threshold-2" class="slide level2" data-background-color="#FFFFFF">
<h2>Peak Over Threshold</h2>
<ul>
<li>Again, let <span class="math inline">\(X_1, \ldots, X_n\)</span> be a sequence of independent random variables with a common distribution function <span class="math inline">\(F\)</span>.</li>
<li>We can consider our extreme values in terms of their <strong>threshold excess</strong> (how much they exceed the threshold by).</li>
<li>For an extreme value <span class="math inline">\(X &gt; u\)</span>, its threshold excess is given as <span class="math inline">\(y = X - u\)</span>.</li>
</ul>

<img data-src="figures/POT.png" style="width:100.0%" class="r-stretch"></section>
<section id="peak-over-threshold-3" class="slide level2">
<h2>Peak Over Threshold</h2>
<p>The probability of threshold excess of size <span class="math inline">\(y\)</span> is given by</p>
<p><span class="math display">\[
\begin{aligned}
P(X &gt; u+y~|~X &gt; u) &amp;= \frac{P(X&gt;u+y)}{P(X&gt;u)} \quad\text{where } y &gt; 0\\
&amp;=  \frac{1 - F(u + y)}{1 - F(u)}
\end{aligned}
\]</span></p>

<img data-src="figures/POT2.png" class="quarto-figure quarto-figure-center r-stretch" style="width:50.0%"></section>
<section id="generalised-pareto" class="slide level2">
<h2>Generalised Pareto</h2>
<ul>
<li>The function <span class="math inline">\(F\)</span> is still unknown, but the distribution of all threshold excesses can be approximated by a <strong>Generalised Pareto distribution (GPD)</strong>.</li>
<li>The cdf of the Generalised Pareto distribution is given by <span class="math display">\[
P(X \leq y~|~X&gt;u) = G(y) =
\begin{cases}
1 - \left( 1 + \frac{\xi (y-u)}{\sigma} \right)^{-\frac{1}{\xi}} &amp; \xi \neq 0\\
1 - \exp \left( - \frac{y-u}{\sigma} \right) &amp; \xi = 0
\end{cases}
\]</span></li>
<li>Again, <span class="math inline">\(u\)</span> is the location parameter, <span class="math inline">\(\sigma\)</span> is the scale parameter and <span class="math inline">\(\xi\)</span> is the shape parameter.</li>
</ul>
</section>
<section id="return-levels-for-pot-models" class="slide level2">
<h2>Return Levels for POT Models</h2>
<ul>
<li>We can define a return level for POT models in a roughly similar way to block maxima models.</li>
<li>The <span class="math inline">\(m\)</span>-observation return level, <span class="math inline">\(x_m\)</span> is defined as the level expected to be exceeded once every <span class="math inline">\(m\)</span> observations, with <span class="math display">\[
x_m =
\begin{cases}
u + \frac{\sigma}{\xi} \left[ \left(m P(X&gt;u)\right)^\xi - 1 \right] &amp; \xi \neq 0\\
u + \sigma \log\left(m P(X&gt;u)\right) &amp; \xi = 0
\end{cases}
\]</span></li>
<li>For any given observation, the probability of exceeding <span class="math inline">\(x_m\)</span> is simply <span class="math inline">\(\frac{1}{m}\)</span>.</li>
</ul>
</section>
<section id="derivation-of-the-return-level-when-xi0" class="slide level2 smaller">
<h2>Derivation of the return level when <span class="math inline">\(\xi=0\)</span></h2>
<div class="columns">
<div class="column" style="width:40%;">
<p>Recall that</p>
<ol type="1">
<li>the probability of exceeding <span class="math inline">\(x_m\)</span> is given by</li>
</ol>
<p><span class="math display">\[
\begin{aligned}
\mathbb{Pr}(x &gt; x_m) &amp;= \mathbb{Pr}(x &gt; x_m|x &gt; u)\mathbb{Pr}(x&gt;u) \\
&amp;= 1/m
\end{aligned}
\]</span></p>
<ol start="2" type="1">
<li>the GEV with <span class="math inline">\(\xi = 0\)</span> is</li>
</ol>
<p><span class="math display">\[\underbrace{G(x_m)}_{\mathbb{Pr}(x\leq x_m | x &gt;u)} = 1- \underbrace{\exp \left(-\dfrac{x_m -u}{\sigma}\right)}_{\mathbb{Pr}(x&gt;x_m|x&gt;u)}\]</span></p>
</div><div class="column" style="width:60%;">
<div style="height: 50px;">

</div>
<p><span class="math display">\[
\begin{aligned}
\mathbb{Pr}(x &gt; x_m) &amp;= \mathbb{Pr}(x &gt; x_m|x &gt; u)\mathbb{Pr}(x&gt;u)\\
&amp; \class{fragment}{ = \exp \left(-\dfrac{x_m -u}{\sigma}\right) \mathbb{Pr}(x&gt;u) = \frac{1}{m}}\\
&amp; \class{fragment}{ \Rightarrow ~ \exp \left(-\dfrac{x_m -u}{\sigma}\right) = \dfrac{1}{m\mathbb{Pr}(x&gt;u)}}\\
&amp; \class{fragment}{-\dfrac{x_m -u}{\sigma}= \log (1) -\log (m\mathbb{Pr}(x&gt;u))} \\
  &amp;~~~~~~~~~~~~~~~~~~~\class{fragment}{\vdots} \\
&amp;~~~~~~~~~~~~ \class{fragment}{x_m =  u + \sigma \log (m\mathbb{Pr}(x&gt;u))}
\end{aligned}
\]</span></p>
</div></div>
</section>
<section id="choosing-a-threshold" class="slide level2" data-background-color="#FFFFFF">
<h2>Choosing a Threshold</h2>
<ul>
<li>We need a threshold low enough that we have sufficient data, but high enough that values above it are genuinely extreme.</li>
</ul>

<img data-src="figures/Thresholds.png" class="quarto-figure quarto-figure-center r-stretch" style="width:65.0%"></section>
<section id="choosing-a-threshold-1" class="slide level2">
<h2>Choosing a Threshold</h2>
<div>
<ul>
<li class="fragment">Occasionally there is a natural choice of threshold (e.g., a legal limit for a pollutant), but generally we need to choose it.</li>
<li class="fragment">One approach is to use a <strong>mean residual life plot</strong>, which plots the sample mean excess (mean of <span class="math inline">\(x&gt;u\)</span>) at a variety of thresholds <span class="math inline">\(u\)</span>.</li>
<li class="fragment">If the GPD is appropriate, the mean excess should be linearly related to the threshold.</li>
<li class="fragment">Therefore, we can identify a suitable threshold as one which lies within an area of linearity on this plot.</li>
</ul>
</div>
</section>
<section id="example---fort-collins-colorado" class="slide level2" data-background-color="#FFFFFF">
<h2>Example - Fort Collins, Colorado</h2>
<ul>
<li>We have daily precipitation data from 1900-1999, obtained from a rain gauge in Fort Collins, Colorado, taken from Katz et al, 2002.</li>
</ul>

<img data-src="figures/FortCollinsData.png" class="quarto-figure quarto-figure-center r-stretch"></section>
<section id="example---fort-collins-colorado-1" class="slide level2" data-background-color="#FFFFFF">
<h2>Example - Fort Collins, Colorado</h2>
<p>We compare three different choices of threshold below (<span class="math inline">\(u = 0.5, 1.0, 1.5\)</span>) to show the importance of getting the choice right.</p>
<div class="columns">
<div class="column" style="width:70%;">
<p><img data-src="figures/FortCollinsThresholds.png" style="width:100.0%" data-fig-aligna="center"></p>
</div><div class="column" style="width:30%;">
<table class="caption-top">
<thead>
<tr class="header">
<th><span class="math inline">\(u\)</span></th>
<th><span class="math inline">\(\% &gt; u\)</span></th>
<th><span class="math inline">\(n &gt; u\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0.5</td>
<td>2.08</td>
<td>759</td>
</tr>
<tr class="even">
<td>1.0</td>
<td>0.58</td>
<td>213</td>
</tr>
<tr class="odd">
<td>1.5</td>
<td>0.25</td>
<td>91</td>
</tr>
</tbody>
</table>
</div></div>
</section>
<section id="mean-residual-life-plot" class="slide level2" data-background-color="#FFFFFF">
<h2>Mean Residual Life Plot</h2>
<ul>
<li>We can fit a mean residual life plot to identify a sensible choice of threshold.</li>
<li>It appears that a value of <span class="math inline">\(u\)</span> somewhere between 1.2 and 1.8 would be an appropriate choice here - this is where the plot appears to be linear.</li>
</ul>

<img data-src="figures/MeanResidualPlot.png" class="quarto-figure quarto-figure-center r-stretch" style="width:100.0%"></section>
<section id="sensitivity-analysis" class="slide level2" data-background-color="#FFFFFF">
<h2>Sensitivity Analysis</h2>
<ul>
<li>We can also carry out a sensitivity analysis to see the effect of choosing different threshold values on the estimated model parameters.</li>
<li>The plot below shows the parameter estimates at different thresholds - they seem fairly robust.</li>
</ul>

<img data-src="figures/Sensitivity.png" class="quarto-figure quarto-figure-center r-stretch" style="width:60.0%"></section>
<section id="pot-models-in-r" class="slide level2">
<h2>POT Models in R</h2>
<ul>
<li>We can use the <code>extRemes</code> package to fit a Generalised Pareto distribution in R.</li>
<li>The function <code>fevd</code> allows several extreme value distributions (including GEV and GPD) to be fitted, and can also provide return levels.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a></a>fitGP <span class="ot">&lt;-</span> <span class="fu">fevd</span>(Fort, <span class="at">threshold=</span><span class="fl">1.5</span>, <span class="at">type=</span><span class="st">"GP"</span>,</span>
<span id="cb6-2"><a></a>                    <span class="at">time.units=</span><span class="st">"365/year"</span>)</span>
<span id="cb6-3"><a></a></span>
<span id="cb6-4"><a></a><span class="fu">return.level</span>(fitGP, <span class="fu">c</span>(<span class="dv">10</span>,<span class="dv">20</span>,<span class="dv">100</span>), <span class="at">type=</span><span class="st">"GP"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<pre><code>[1] "Return Levels for period units in years"
 10-year level  20-year level 100-year level
      2.857184       3.340219       4.581339</code></pre>
</section>
<section id="correlation" class="slide level2">
<h2>Correlation</h2>
<div>
<ul>
<li class="fragment"><p>Threshold exceedances are not always independent due to temporal correlation.</p></li>
<li class="fragment"><p>If we have high temperatures today, it’s likely we might also have high temperatures tomorrow.</p></li>
<li class="fragment"><p>We have to account for this dependence within our model, for example by using the autoregressive approaches outlined in the time series section.</p></li>
<li class="fragment"><p>Alternatively, we could use a ‘declustering’ approach which identifies these temporal clusters and simply uses the cluster maxima.</p></li>
</ul>
</div>
</section>
<section id="summary" class="slide level2">
<h2>Summary</h2>
<div>
<ul>
<li class="fragment"><p>Estimating extremes is challenging and the results can be unreliable even with large datasets.</p></li>
<li class="fragment"><p>We have identified two main approaches for dealing with these data - block maxima and point over threshold.</p></li>
<li class="fragment"><p>The block maxima approach uses the Generalised Extreme Value (GEV) distribution to model the highest value(s) within a specific block of time.</p></li>
<li class="fragment"><p>The point over threshold approach uses the Generalised Pareto distribution (GPD) to model all observations which exceed a certain value.</p></li>
</ul>
</div>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="UofG.png" class="slide-logo"></p>
<div class="footer footer-default">
<p><a href="https://envstats-stats4009-stats503.github.io/Course_Notes/2025_26/Module_2/docs/" style="color:#ccc; padding:20px 30px; display:inline-block; margin:-20px -30px;">Home</a></p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    

    <script>

      // htmlwidgets need to know to resize themselves when slides are shown/hidden.

      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current

      // slide changes (different for each slide format).

      (function () {

        // dispatch for htmlwidgets

        function fireSlideEnter() {

          const event = window.document.createEvent("Event");

          event.initEvent("slideenter", true, true);

          window.document.dispatchEvent(event);

        }

    

        function fireSlideChanged(previousSlide, currentSlide) {

          fireSlideEnter();

    

          // dispatch for shiny

          if (window.jQuery) {

            if (previousSlide) {

              window.jQuery(previousSlide).trigger("hidden");

            }

            if (currentSlide) {

              window.jQuery(currentSlide).trigger("shown");

            }

          }

        }

    

        // hookup for slidy

        if (window.w3c_slidy) {

          window.w3c_slidy.add_observer(function (slide_num) {

            // slide_num starts at position 1

            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);

          });

        }

    

      })();

    </script>

    

    <script id="quarto-html-after-body" type="application/javascript">
    window.document.addEventListener("DOMContentLoaded", function (event) {
      const toggleBodyColorMode = (bsSheetEl) => {
        const mode = bsSheetEl.getAttribute("data-mode");
        const bodyEl = window.document.querySelector("body");
        if (mode === "dark") {
          bodyEl.classList.add("quarto-dark");
          bodyEl.classList.remove("quarto-light");
        } else {
          bodyEl.classList.add("quarto-light");
          bodyEl.classList.remove("quarto-dark");
        }
      }
      const toggleBodyColorPrimary = () => {
        const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
        if (bsSheetEl) {
          toggleBodyColorMode(bsSheetEl);
        }
      }
      toggleBodyColorPrimary();  
      const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
      tabsets.forEach(function(tabset) {
        const tabby = new Tabby('#' + tabset.id);
      });
      const isCodeAnnotation = (el) => {
        for (const clz of el.classList) {
          if (clz.startsWith('code-annotation-')) {                     
            return true;
          }
        }
        return false;
      }
      const onCopySuccess = function(e) {
        // button target
        const button = e.trigger;
        // don't keep focus
        button.blur();
        // flash "checked"
        button.classList.add('code-copy-button-checked');
        var currentTitle = button.getAttribute("title");
        button.setAttribute("title", "Copied!");
        let tooltip;
        if (window.bootstrap) {
          button.setAttribute("data-bs-toggle", "tooltip");
          button.setAttribute("data-bs-placement", "left");
          button.setAttribute("data-bs-title", "Copied!");
          tooltip = new bootstrap.Tooltip(button, 
            { trigger: "manual", 
              customClass: "code-copy-button-tooltip",
              offset: [0, -8]});
          tooltip.show();    
        }
        setTimeout(function() {
          if (tooltip) {
            tooltip.hide();
            button.removeAttribute("data-bs-title");
            button.removeAttribute("data-bs-toggle");
            button.removeAttribute("data-bs-placement");
          }
          button.setAttribute("title", currentTitle);
          button.classList.remove('code-copy-button-checked');
        }, 1000);
        // clear code selection
        e.clearSelection();
      }
      const getTextToCopy = function(trigger) {
          const codeEl = trigger.previousElementSibling.cloneNode(true);
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
      }
      const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
        text: getTextToCopy
      });
      clipboard.on('success', onCopySuccess);
      if (window.document.getElementById('quarto-embedded-source-code-modal')) {
        const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
          text: getTextToCopy,
          container: window.document.getElementById('quarto-embedded-source-code-modal')
        });
        clipboardModal.on('success', onCopySuccess);
      }
        var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
        var mailtoRegex = new RegExp(/^mailto:/);
          var filterRegex = new RegExp('/' + window.location.host + '/');
        var isInternal = (href) => {
            return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
        }
        // Inspect non-navigation links and adorn them if external
     	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
        for (var i=0; i<links.length; i++) {
          const link = links[i];
          if (!isInternal(link.href)) {
            // undo the damage that might have been done by quarto-nav.js in the case of
            // links that we want to consider external
            if (link.dataset.originalHref !== undefined) {
              link.href = link.dataset.originalHref;
            }
          }
        }
      function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
        const config = {
          allowHTML: true,
          maxWidth: 500,
          delay: 100,
          arrow: false,
          appendTo: function(el) {
              return el.closest('section.slide') || el.parentElement;
          },
          interactive: true,
          interactiveBorder: 10,
          theme: 'light-border',
          placement: 'bottom-start',
        };
        if (contentFn) {
          config.content = contentFn;
        }
        if (onTriggerFn) {
          config.onTrigger = onTriggerFn;
        }
        if (onUntriggerFn) {
          config.onUntrigger = onUntriggerFn;
        }
          config['offset'] = [0,0];
          config['maxWidth'] = 700;
        window.tippy(el, config); 
      }
      const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
      for (var i=0; i<noterefs.length; i++) {
        const ref = noterefs[i];
        tippyHover(ref, function() {
          // use id or data attribute instead here
          let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
          try { href = new URL(href).hash; } catch {}
          const id = href.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note) {
            return note.innerHTML;
          } else {
            return "";
          }
        });
      }
      const findCites = (el) => {
        const parentEl = el.parentElement;
        if (parentEl) {
          const cites = parentEl.dataset.cites;
          if (cites) {
            return {
              el,
              cites: cites.split(' ')
            };
          } else {
            return findCites(el.parentElement)
          }
        } else {
          return undefined;
        }
      };
      var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
      for (var i=0; i<bibliorefs.length; i++) {
        const ref = bibliorefs[i];
        const citeInfo = findCites(ref);
        if (citeInfo) {
          tippyHover(citeInfo.el, function() {
            var popup = window.document.createElement('div');
            citeInfo.cites.forEach(function(cite) {
              var citeDiv = window.document.createElement('div');
              citeDiv.classList.add('hanging-indent');
              citeDiv.classList.add('csl-entry');
              var biblioDiv = window.document.getElementById('ref-' + cite);
              if (biblioDiv) {
                citeDiv.innerHTML = biblioDiv.innerHTML;
              }
              popup.appendChild(citeDiv);
            });
            return popup.innerHTML;
          });
        }
      }
    });
    </script>
    

</body></html>