---
title: "Module 2"
subtitle: "Measuring Environmental Change"
author:
  - name: Jafet Belmont
    email: Jafet.Belmont@glasgow.ac.uk
format: 
  html: 
    embed-resources: false
    fontsize: "12"
    mainfont: serif
    number-sections: true
  PrettyPDF-pdf:
    number-sections: true
execute: 
  freeze: auto
filters: 
  - shinylive
editor_options: 
  chunk_output_type: console
---

# Overview

This module provides the theoretical foundation and practical skills for analysing temporal environmental and ecological data, with emphasis on quantifying ecological trends, detecting structural changes, and modelling extremes. Using contemporary environmental challenges as case studies, we will learn how to extract meaningful signals from noisy temporal data and make robust inferences about environmental change.

We will focus on methods that move beyond modelling central tendencies to explicitly quantify what happens at the tails of distributions—where many critical environmental phenomena occur. Floods, droughts, heatwaves, and other extremes define system boundaries, drive ecological transitions, and inform the design of critical infrastructure.

# Course Structure

This course provides an appreciation of the application of statistical methods and concepts to problems in *Environmental and Ecological Sciences*.

The course consists of 3 modules divided into weeks - this is primarily to help you find the relevant material easily.

| Module | Week | Topic |
|:----------------------:|:----------------------:|:----------------------:|
| Environmental Monitoring & Data processing | 1 | Introduction to Environmental Statistics |
|  | 2 | Understanding our Data |
|  | 3 | Sampling and Monitoring Networks |
| Measuring Environmental Change | 4 | [Assessing Change Over Time](notes/notes_1.qmd) |
|  | 5 | [Temporal Correlation and Changepoints](notes/notes_2.qmd) |
|  | 6 | [Modelling Environmental Extremes](notes/notes_3.qmd) |
| Spatial Modelling in Ecology | 7 | Modelling Areal Data |
|  | 8 | Modelling Geostatistical Data|
|  | 9 | Methods for Point referrenced Data |

## Lectures

There will be two - 1 hr lectures per week at [42 Bute Gardens:916](https://www.gla.ac.uk/apps/uofglife/#/map?buildingId=322&toId=3220916&toType=R)


::: callout-note
*Lectures will be recorded if the room’s technology allows them to be.*
:::

## Tutorials

In addition, there will be **four** tutorials for this course. There are two tutorial groups - please check on MyCampus which one you are in.

:::: panel-tabset
# Tutorial Group 1 - Monday 10am

**Tutorial groups:**

-   STATS 4009 - TU01 (23738)

-   STATS 5031 - TU01 (24174)

**Venue:**

[Adam Smith: 281](https://www.gla.ac.uk/apps/uofglife/#/map?buildingId=W22&toId=W220281&toType=R)

**Tutorial dates:**

1.  26-Jan-2026

2.  [09-Feb-2026](notes/tutorial_sheet_2.qmd)

3.  [23-Feb-2026](notes/tutorial_sheet_3.qmd)

4.  09-Mar-2026

# Tutorial Group 2- Wednesday 12 noon

**Tutorial groups:**

-   STATS 4009 - TU02 (23739)

-   STATS 5031 - TU02 (24175)

**Venue:**

[Joseph Black Building:C407 Agricult](https://www.gla.ac.uk/apps/uofglife/#/map?buildingId=124&toId=124C407&toType=R)[m](https://www.gla.ac.uk/apps/uofglife/#/map?buildingId=W23&toId=W230311B&toType=R)

**Tutorial dates:**

1.  28 -Jan-2026

2.  [11-Feb-2026](notes/tutorial_sheet_2.qmd)

3.  [25-Feb-2026](notes/tutorial_sheet_3.qmd)

4.  11-Mar-2026


::::

::: callout-important
*You are expected to have attempted the exercise sheets before the tutorial - they will be available in advance.*
:::

## Labs

There will be three labs taking place in [Boyd Orr Building:418 Lab](https://www.gla.ac.uk/apps/uofglife/#/map?buildingId=295&toId=2950418&toType=R) from **15:00-17:00pm** on the following dates (clicking on the date will direct you to the lab material):

1.  Lab session 1 - Jan 30th

2.  [Lab session 2 - Feb 27th](lab_2.qmd)

3.  March 13th

# Assessments

Assessment in this course includes continuous assessment and a final exam. The exam will take place in April/May.

-   *Level H* students will have a **Group Report** worth 25% and a\
    final exam worth 75%.

-   *Level M* students will have a **Group Report** worth 25%, a\
    **critique** worth 10% and a final exam worth 65%.
